log_dir: D:\Models\GenoPhen\Pretraining\Geno
training:
  mlm_probability: 0.15
optimizer:
  lr: 0.00025
species:
  E_Coli:
    file_path: /media/david/T7/NCBI/E.Coli.Shigella/PDG000000004.3840.amr.metadata.tsv
  Kleb:
    file_path: /media/david/T7/NCBI/Klebsiella/PDG000000012.1486.amr.metadata.tsv
data:
  load_preprocessed_data: False
  preprocessed_data_file_path: D:\Models\GenoPhen\Pretraining\Geno\PT_Hier3\pp_data.tsv
  species:
    - E_Coli
  columns:
    - AMR_genotypes_core
  filter:
    point: False
    partial: True
    partial_contig: True
    mistranslation: True
    hmm: True
    bla: True
    aph_aac: True
    doubles_pheno: True
    doubles_geno: False
    forward_slash: True
    min_geno: 3
    min_ab: 0
  known_gene: 3
  hierarchy:
    use_hierarchy_data: True
    hierarchy_variant: summed
    hierarchy_file_path: /media/david/T7/NCBI/ReferenceGeneHierarchy.txt
    catalog_file_path: /media/david/T7/NCBI/ReferenceGeneCatalog.txt