model:
  class: IntegratedModel
  hidden_dim: 200
  input_dim: 991
  out_dim: 2
  pheno:
    use_pretrained: True
    pretrained_weights: D:\Models\GenoPhen\Pretraining\Pheno\Legacy\bert_updated.pt
    class: AntibioticModelTrain
    num_hiddens: 64
    norm_shape: 64
    ffn_num_input: 64
    ffn_num_hiddens: 128
    attention_heads: 1
    attention_layers: 2
    dropout: 0.05
    key_size: 64
    query_size: 64
    value_size: 64
  geno:
    use_pretrained: True
    pretrained_weights: D:\Models\GenoPhen\Pretraining\Geno\pytorch_model.bin
    class: RobertaModel
    n_attention_heads: 4
    n_hidden_layers: 4
    hidden_size: 64
tokenizer:
  use_pretrained: True
  pheno:
    pretrained_weights: D:\Models\GenoPhen\Pretraining\Pheno\Legacy\vocabulary.pth
  geno:
    pretrained_weights: D:\Models\GenoPhen\Pretraining\Geno