model:
  class: RobertaHierForMaskedLM
  n_attention_heads: 4
  n_hidden_layers: 4
  hidden_size: 512
tokenizer:
  use_pretrained: False
  class: RobertaTokenizer
  max_len: 250
  special_token_list:
    - <s>
    - <pad>
    - </s>
    - <mask>
    - <unk>
    - <gpsep>