log_dir: D:\Models\GenoPhen\Finetuning
training:
  n_epochs: 50
  val_every_n_epochs: 2
optimizer:
  lr: 0.000001
data:
  species:
    - E_Coli
  columns:
    - AMR_genotypes_core
    - AST_phenotypes
  filter:
    point: False
    partial: True
    partial_contig: True
    mistranslation: True
    hmm: True
    bla: True
    aph_aac: True
    min_geno: 1
    min_ab: 4
  known_ab: 3
  known_gene: -1