log_dir: D:\Models\GenoPhen\Finetuning
training:
  n_epochs: 50
  val_every_n_epochs: 2
optimizer:
  lr: 0.000001
data:
  load_preprocessed_data: False
  preprocessed_data_file_path: D:\Models\GenoPhen\Pretraining\Geno\PT_Hier\pp_data.tsv
  species:
    - E_Coli
  columns:
    - AMR_genotypes_core
    - AST_phenotypes
  filter:
    point: False
    partial: True
    partial_contig: True
    mistranslation: True
    hmm: True
    bla: True
    aph_aac: True
    doubles_pheno: True
    doubles_geno: False
    min_geno: 1
    min_ab: 2
  known_ab: 1
  known_gene: 1
  hierarchy:
    use_hierarchy_data: True
    hierarchy_variant: summed
    hierarchy_file_path: /media/david/T7/NCBI/ReferenceGeneHierarchy.txt
    catalog_file_path: /media/david/T7/NCBI/ReferenceGeneCatalog.txt